20 instagram integration
ISDStudentsInitiative/DaWay pull request #34
Opened 2018-02-03 21:05 UTC by Dicrit

Good way to start. Controller is needed to be reworked in future when authorization will be implemented.

2018-02-07 11:49 UTC, msvaillant requested changes

2018-02-07 11:49 UTC, msvaillant commented on InstaBotPrototype/InstaBotLibrary/Instagram/InstagramUnauthorizedException.cs
> +        public InstagramUnauthorizedException() : base("Instagram wasn't auntificated, please use Auth method before")
typo - authentification

2018-02-07 11:49 UTC, msvaillant commented on InstaBotPrototype/InstaBotPrototype/InstaBotPrototype.csproj
> +    <PackageReference Include="InstaSharp" Version="2.0.6" />
I think is not needed in Web part

2018-02-07 11:49 UTC, msvaillant commented on InstaBotPrototype/InstaBotPrototype/Instagram/Controllers/InstagramController.cs
> +            instagramService = new InstagramService(configuration);
Inject and register service first, don't use NEW keyword, use ASP.Net Core DI instead

2018-02-07 11:49 UTC, msvaillant commented on InstaBotPrototype/InstaBotLibrary/Instagram/InstagramService.cs
> +        public InstagramService(IConfiguration configuration)
read this article first
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options

2018-02-07 11:56 UTC, Dicrit commented on InstaBotPrototype/InstaBotPrototype/InstaBotPrototype.csproj
> +    <PackageReference Include="InstaSharp" Version="2.0.6" />
Completely agree. It left from time when all logic was on the main project.

2018-02-16 17:34 UTC, msvaillant approved these changes

2018-02-16 17:34 UTC, merged