9 authorization
ISDStudentsInitiative/DaWay pull request #35
Opened 2018-02-09 00:30 UTC by OlgaLisniak

Some functions require refactoring.
Not quite the final version

2018-02-09 07:17 UTC, Dicrit requested changes
Это то, что касается только твоих изменений. Возможно, после rebase на develop будут еще вопросы.

2018-02-09 07:17 UTC, Dicrit commented on InstaBotPrototype/InstaBotPrototype/Services/UserManager.cs
> +        UserRepository userRepository = new UserRepository();
new? Maybee add it in constructor?

2018-02-09 07:17 UTC, Dicrit commented on InstaBotPrototype/InstaBotPrototype/Services/UserManager.cs
> +                return false; ;
double ";". For what?

2018-02-16 17:39 UTC, msvaillant requested changes
I see lots of mess from different app version here. discuss with @Dicrit your feature request and remove obsolete code

2018-02-17 17:21 UTC, closed without merging